# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=roastnotes
      - POSTGRES_PASSWORD=roast123
      - POSTGRES_DB=roastnotes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
