"""add group roast collection and cached stats

Revision ID: 1c1531a1c138
Revises: 0b5bdd2a6636
Create Date: 2025-02-12 08:37:39.015317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c1531a1c138'
down_revision: Union[str, None] = '0b5bdd2a6636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grouproastcollection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('roast_id', sa.Integer(), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cached_group_rating_stats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['roast_id'], ['roast.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('roast', sa.Column('cached_rating_stats', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roast', 'cached_rating_stats')
    op.drop_table('grouproastcollection')
    # ### end Alembic commands ###
