"""roast update bean details addition

Revision ID: 0b5bdd2a6636
Revises: f18b6a454e3a
Create Date: 2025-02-11 09:33:10.620198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b5bdd2a6636'
down_revision: Union[str, None] = 'f18b6a454e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE roastlevel AS ENUM ('unspecified', 'light', 'medium', 'dark')")
    
    op.create_table('beandetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roast_id', sa.Integer(), nullable=False),
    sa.Column('species', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cultivar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processing_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['roast_id'], ['roast.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('roast', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('roast', sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('roast', sa.Column('single_origin', sa.Boolean(), nullable=False))
    op.add_column('roast', sa.Column('roast_level', sa.Enum('unspecified', 'light', 'medium', 'dark', name='roastlevel'), nullable=True))
    op.add_column('roast', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('roast', 'bean_details')
    op.drop_column('roast', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roast', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('roast', sa.Column('bean_details', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('roast', 'created_at')
    op.drop_column('roast', 'roast_level')
    op.drop_column('roast', 'single_origin')
    op.drop_column('roast', 'origin')
    op.drop_column('roast', 'name')
    op.drop_table('beandetails')
    op.execute("DROP TYPE roastlevel")
    # ### end Alembic commands ###
